# Przygotowanie danych do modelowania

## Operacje na danych

In [ ]:
# import bibliotek
import pandas as pd
import plotly.express as px
import plotly.figure_factory as ff
import plotly.graph_objects as go
import numpy as np

from sklearn import preprocessing
from sklearn import compose
from sklearn import covariance
from sklearn import impute
from sklearn import model_selection

In [ ]:
# ustawienie ziarna losowosci
#np.random.seed(1)

# tworzenie zbioru danych
dane = np.random.rand(20, 2)
dane

array([[0.03768415, 0.7665388 ],
       [0.08932555, 0.46996333],
       [0.42056604, 0.6980628 ],
       [0.3188702 , 0.95229091],
       [0.41834782, 0.19593658],
       [0.45943984, 0.81317965],
       [0.08658088, 0.95435151],
       [0.51079251, 0.95037875],
       [0.8150934 , 0.97122171],
       [0.07767635, 0.08235437],
       [0.98724676, 0.33365397],
       [0.99615706, 0.08747575],
       [0.93912073, 0.38177257],
       [0.71969511, 0.66767633],
       [0.51950164, 0.80756396],
       [0.35830164, 0.90964648],
       [0.63798399, 0.8754465 ],
       [0.7957605 , 0.9114592 ],
       [0.84839125, 0.55172426],
       [0.43898713, 0.25975086]])

### Skalowanie zmiennych

Wzór na przeskalowanie w skali od 0 do 1:<br>
![skalowanie](https://akademiadatascience.s3-eu-west-1.amazonaws.com/materialy/sds/modul6/skalowanie.png)

In [ ]:
print("Dane przed skalowaniem:\n", dane)

Dane przed skalowaniem:
 [[0.03768415 0.7665388 ]
 [0.08932555 0.46996333]
 [0.42056604 0.6980628 ]
 [0.3188702  0.95229091]
 [0.41834782 0.19593658]
 [0.45943984 0.81317965]
 [0.08658088 0.95435151]
 [0.51079251 0.95037875]
 [0.8150934  0.97122171]
 [0.07767635 0.08235437]
 [0.98724676 0.33365397]
 [0.99615706 0.08747575]
 [0.93912073 0.38177257]
 [0.71969511 0.66767633]
 [0.51950164 0.80756396]
 [0.35830164 0.90964648]
 [0.63798399 0.8754465 ]
 [0.7957605  0.9114592 ]
 [0.84839125 0.55172426]
 [0.43898713 0.25975086]]


In [ ]:
# definiowanie zakresu skalowania danych
scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))

# skalowanie danych
skalowane_dane = scaler.fit_transform(dane)
print("Dane przeskalowane:\n", skalowane_dane)
print("\n")
print("Min:", skalowane_dane.min(axis=0))
print("\n")
print("Max", skalowane_dane.max(axis=0))

Dane przeskalowane:
 [[0.         0.76972614]
 [0.05387883 0.43607065]
 [0.39947074 0.69268877]
 [0.2933688  0.97870233]
 [0.39715641 0.12778309]
 [0.44002881 0.82219838]
 [0.05101524 0.98102057]
 [0.4936064  0.9765511 ]
 [0.81109152 1.        ]
 [0.04172491 0.        ]
 [0.99070365 0.28271891]
 [1.         0.00576169]
 [0.94049249 0.33685365]
 [0.71155997 0.65850316]
 [0.50269286 0.81588056]
 [0.33450865 0.93072619]
 [0.62630862 0.89225027]
 [0.79092099 0.93276554]
 [0.84583204 0.52805392]
 [0.41868995 0.19957589]]


Min: [0. 0.]


Max [1. 1.]


In [ ]:
# rozkład pierwszej kolumny
ff.create_distplot([skalowane_dane[:,0]], ["skalowanie"])

### Normalizacja zmiennych

Wzór na normalizację, gdzie suma elementów wynosi 1:<br>
![normalizacja](https://akademiadatascience.s3-eu-west-1.amazonaws.com/materialy/sds/modul6/norm_miejska.png)

In [ ]:
print("Dane przed normalizacją:\n", dane)

Dane przed normalizacją:
 [[0.03768415 0.7665388 ]
 [0.08932555 0.46996333]
 [0.42056604 0.6980628 ]
 [0.3188702  0.95229091]
 [0.41834782 0.19593658]
 [0.45943984 0.81317965]
 [0.08658088 0.95435151]
 [0.51079251 0.95037875]
 [0.8150934  0.97122171]
 [0.07767635 0.08235437]
 [0.98724676 0.33365397]
 [0.99615706 0.08747575]
 [0.93912073 0.38177257]
 [0.71969511 0.66767633]
 [0.51950164 0.80756396]
 [0.35830164 0.90964648]
 [0.63798399 0.8754465 ]
 [0.7957605  0.9114592 ]
 [0.84839125 0.55172426]
 [0.43898713 0.25975086]]


In [ ]:
# zdefiniowanie normalizatora l1 - norma Manhattan
norm = preprocessing.Normalizer(norm="l1")

# normalizacja danych
norm_dane = norm.transform(dane)
print("Dane znormalizowane:\n", norm_dane)
print("\n")
print("Suma wg. wierszy:", norm_dane.sum(axis=1))

Dane znormalizowane:
 [[0.04685784 0.95314216]
 [0.15971272 0.84028728]
 [0.37596567 0.62403433]
 [0.25084956 0.74915044]
 [0.68103279 0.31896721]
 [0.36101902 0.63898098]
 [0.08317627 0.91682373]
 [0.34957744 0.65042256]
 [0.45629878 0.54370122]
 [0.48538399 0.51461601]
 [0.7474042  0.2525958 ]
 [0.91927547 0.08072453]
 [0.71097395 0.28902605]
 [0.51874724 0.48125276]
 [0.39146644 0.60853356]
 [0.28258383 0.71741617]
 [0.42154826 0.57845174]
 [0.46611488 0.53388512]
 [0.60594376 0.39405624]
 [0.62825714 0.37174286]]


Suma wg. wierszy: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# rozkład pierwszej kolumny
ff.create_distplot([norm_dane[:,0]], ["normalizacja"])

### Standaryzacja zmiennych

Wzór na standaryzację, gdzie średnia wynosi 0 a odchylenie standardowe 1:<br>
![normalizacja](https://akademiadatascience.s3-eu-west-1.amazonaws.com/materialy/sds/modul6/stand.png)

In [ ]:
print("Dane przed standaryzacją:\n", dane)

Dane przed standaryzacją:
 [[0.06595759 0.70121601]
 [0.30864292 0.90333974]
 [0.40906141 0.17049681]
 [0.4448264  0.39027434]
 [0.02194855 0.31628816]
 [0.38541612 0.09640784]
 [0.3629956  0.35253438]
 [0.93668957 0.95480242]
 [0.47516132 0.60271916]
 [0.83493964 0.6514887 ]
 [0.4507045  0.66538524]
 [0.11896567 0.67698075]
 [0.72464927 0.03768703]
 [0.14450536 0.1758634 ]
 [0.43985411 0.74548918]
 [0.69927349 0.79091679]
 [0.83740222 0.25581607]
 [0.03821994 0.68816073]
 [0.34890387 0.84667832]
 [0.20076173 0.45590086]]


In [ ]:
# zdefiniowanie standaryzatora
stand = preprocessing.StandardScaler()

# standaryzacja danych
stand_dane = stand.fit_transform(dane)
print("Dane zestandaryzowane:\n", stand_dane)
print("\n")
print("Średnia:", stand_dane.mean(axis=0).round())
print("Odch. standardowe:", stand_dane.std(axis=0))

Dane zestandaryzowane:
 [[-1.60088813  0.44391789]
 [-1.43081312 -0.53481164]
 [-0.33991058  0.21794006]
 [-0.67483415  1.05691898]
 [-0.34721604 -1.43912811]
 [-0.21188417  0.59783752]
 [-1.43985238  1.06371918]
 [-0.04276004  1.05060865]
 [ 0.95942     1.11939257]
 [-1.46917843 -1.81396109]
 [ 1.52638734 -0.98464653]
 [ 1.5557324  -1.79706   ]
 [ 1.36788977 -0.82585021]
 [ 0.64523668  0.11766158]
 [-0.01407753  0.57930514]
 [-0.54497124  0.91618798]
 [ 0.3761305   0.80332452]
 [ 0.89574932  0.92217012]
 [ 1.06908265 -0.26499218]
 [-0.27924284 -1.22853441]]


Średnia: [-0. -0.]
Odch. standardowe: [1. 1.]


In [ ]:
# rozkład pierwszej kolumny
ff.create_distplot([stand_dane[:,0]], ["standaryzacja"])

### Grupowanie zmiennych

In [ ]:
# tworzenie zbioru
dane_2 = np.random.randint(16,100,20).reshape(10,2)
klienci = pd.DataFrame(dane_2, columns=["grupa1", "grupa2"])
print("Dane przed zastosowaniem progów:\n", klienci)

Dane przed zastosowaniem progów:
    grupa1  grupa2
0      49      17
1      95      42
2      50      39
3      55      50
4      28      52
5      98      66
6      55      66
7      69      63
8      44      40
9      38      22


In [ ]:
# ustawienie wartości progowej
prog = preprocessing.Binarizer(50)
# zastosowanie progu
prog.fit_transform(klienci)

array([[0, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0]])

In [ ]:
# zastosowanie kilku wartości progowych
klienci_prog = np.digitize(klienci, bins=[18,26,50])
print("Dane przed zastosowaniem progów:\n", klienci)
print("\n")
print("Dane po zastosowaniu progów:\n", klienci_prog)

Dane przed zastosowaniem progów:
    grupa1  grupa2
0      49      17
1      95      42
2      50      39
3      55      50
4      28      52
5      98      66
6      55      66
7      69      63
8      44      40
9      38      22


Dane po zastosowaniu progów:
 [[2 0]
 [3 2]
 [3 2]
 [3 3]
 [2 3]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [2 1]]


Wskazówka: jest możliwość użycia argumentu `right`, który określa:
* `np.digitize(..., right=False)`, dotyczy: `bins[i-1] <= x < bins[i]` (domyślnie)
* `np.digitize(..., right=True)`, dotyczy: `bins[i-1] < x <= bins[i]`


In [ ]:
np.digitize(klienci, bins=[18,26,50], right=True)

array([[2, 0],
       [3, 2],
       [2, 2],
       [3, 2],
       [2, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [2, 2],
       [2, 1]])

### Podmiana wartości brakujących

Wygodny sposób na uzupełnienie wartości brakujących, gdzie argument `strategy` przedstawia strategię uzupełnienia:
* `strategy=mean` - na średnią;
* `strategy=median` - na medianę;
* `strategy=most_frequent` - na najcześciej występująca wartość.


Operacje na danych numerycznych:

In [ ]:
# tworzenie zbioru
braki_danych = pd.DataFrame(np.random.randint(16,100,20).reshape(10,2), columns=["grupa1", "grupa2"])
# usuwanie cześci obserwacji
braki_danych["grupa1"][0] = np.NAN
braki_danych["grupa2"][0] = np.NAN
print(braki_danych)

   grupa1  grupa2
0     NaN     NaN
1    53.0    31.0
2    77.0    65.0
3    57.0    31.0
4    74.0    99.0
5    54.0    94.0
6    75.0    19.0
7    67.0    85.0
8    26.0    73.0
9    65.0    19.0


In [ ]:
# tworzenie imputera
imputer = impute.SimpleImputer(strategy="median")
# wyuczenie i zastosowanie imputera
imputer.fit_transform(braki_danych)

array([[65., 65.],
       [53., 31.],
       [77., 65.],
       [57., 31.],
       [74., 99.],
       [54., 94.],
       [75., 19.],
       [67., 85.],
       [26., 73.],
       [65., 19.]])

In [ ]:
# sprawdzenie
braki_danych.median()

grupa1    65.0
grupa2    65.0
dtype: float64

Operacje na danych tekstowych:

In [ ]:
# tworzenie zbioru
braki_danych_2 = pd.DataFrame([np.NaN, "Michal", "Michal", "Robert", "Arkadiusz", "Anna", "Dorota"], 
                              columns=["imiona"])
# usuwanie warości
#braki_danych_2["imiona"][0] = np.NaN
# tworzenie imputera
imputer_2 = impute.SimpleImputer(strategy="most_frequent", )
# wyuczenie i zastosowanie imputera
imputer_2.fit_transform(braki_danych_2)


array([['Michal'],
       ['Michal'],
       ['Michal'],
       ['Robert'],
       ['Arkadiusz'],
       ['Anna'],
       ['Dorota']], dtype=object)

In [ ]:
braki_danych_2["imiona"].value_counts()

Michal       2
Robert       1
Anna         1
Arkadiusz    1
Dorota       1
Name: imiona, dtype: int64

### Kodowanie kategorii 

Dane dotyczą sprzedaży wideogier wg. różnych platform i regionów. [Więcej o danych...](https://bit.ly/30MpYhb)

In [ ]:
# wczytanie danych
df = pd.read_csv("https://bit.ly/33NOQXD")
print(df.shape)
df.head(10)

(16598, 11)


Rank                       Name  ... Other_Sales  Global_Sales
0     1                 Wii Sports  ...        8.46         82.74
1     2          Super Mario Bros.  ...        0.77         40.24
2     3             Mario Kart Wii  ...        3.31         35.82
3     4          Wii Sports Resort  ...        2.96         33.00
4     5   Pokemon Red/Pokemon Blue  ...        1.00         31.37
5     6                     Tetris  ...        0.58         30.26
6     7      New Super Mario Bros.  ...        2.90         30.01
7     8                   Wii Play  ...        2.85         29.02
8     9  New Super Mario Bros. Wii  ...        2.26         28.62
9    10                  Duck Hunt  ...        0.47         28.31

[10 rows x 11 columns]

In [ ]:
# wyświetlenie kategorii dla wybranej kolumny
df["Genre"].value_counts()

Action          3316
Sports          2346
Misc            1739
Role-Playing    1488
Shooter         1310
Adventure       1286
Racing          1249
Platform         886
Simulation       867
Fighting         848
Strategy         681
Puzzle           582
Name: Genre, dtype: int64

#### LabelEncoder

Wersja krokowa:

In [ ]:
# tworzenie enkodera wg. kolejności
label_encoder = preprocessing.LabelEncoder()
# użycie enkodera
fit = label_encoder.fit(df["Genre"])
fit.transform(df["Genre"])

array([10,  4,  6, ...,  6,  5,  4])

Wersja skrócona:

In [ ]:
# tworzenie enkodera wg. kolejności
label_encoder = preprocessing.LabelEncoder()
# użycie enkodera
label_encoder.fit_transform(df["Genre"])

array([10,  4,  6, ...,  6,  5,  4])

#### LabelBinarizer

In [ ]:
# tworzenie enkodera binarnego
bin_encoder = preprocessing.LabelBinarizer()
# użycie enkodera
bin_encoder.fit_transform(df["Genre"])

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
# wylistowanie klas
bin_encoder.classes_

array(['Action', 'Adventure', 'Fighting', 'Misc', 'Platform', 'Puzzle',
       'Racing', 'Role-Playing', 'Shooter', 'Simulation', 'Sports',
       'Strategy'], dtype='<U12')

#### OneHotEncoder

Domyślnie argument `categories="auto"` - brane są kategorie ze zbioru uczacecho w sposób automatyczny.

In [ ]:
# tworzenie enkodera
hot_encoder = preprocessing.OneHotEncoder()
# użycie enkodera
hot_encoder.fit_transform(df["Genre"].values.reshape(-1,1)).toarray()

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Po przekazaniu argumentu `remainder="passthrough"` wszystkie niezdefiniowane kolumny zostaną uwzględnione po transformacji wybranych.<br>
Domyślnie jest `remainder="drop"`, gdzie otrzymamy tylko ramkę zmienionych kolumn a pozostałe zostana usunięte. 

In [ ]:
# tworzenie inteligentnego enkodera
ihot_encoder = compose.ColumnTransformer(transformers=[("encoder", preprocessing.OneHotEncoder(categories="auto"), 
                                                        ["Genre"])], 
                                         remainder="passthrough")
# użycie enkodera
transformed = ihot_encoder.fit_transform(df)
print(transformed)

[[0.0 0.0 0.0 ... 3.77 8.46 82.74]
 [0.0 0.0 0.0 ... 6.81 0.77 40.24]
 [0.0 0.0 0.0 ... 3.79 3.31 35.82]
 ...
 [0.0 0.0 0.0 ... 0.0 0.0 0.01]
 [0.0 0.0 0.0 ... 0.0 0.0 0.01]
 [0.0 0.0 0.0 ... 0.0 0.0 0.01]]


In [ ]:
# tworzenie inteligentnego enkodera  i przekształcenie w DF
ihot_encoder_2 = compose.ColumnTransformer(transformers=[("encoder", preprocessing.OneHotEncoder(categories="auto"), ["Genre"])], 
                                         remainder="drop")
# użycie enkodera
transformed2 = ihot_encoder_2.fit_transform(df).toarray()
# tworzenie DF
pd.DataFrame(transformed2, columns=["Genre_" + str(a) for a in range(transformed2.shape[1])])

Genre_0  Genre_1  Genre_2  Genre_3  ...  Genre_8  Genre_9  Genre_10  Genre_11
0          0.0      0.0      0.0      0.0  ...      0.0      0.0       1.0       0.0
1          0.0      0.0      0.0      0.0  ...      0.0      0.0       0.0       0.0
2          0.0      0.0      0.0      0.0  ...      0.0      0.0       0.0       0.0
3          0.0      0.0      0.0      0.0  ...      0.0      0.0       1.0       0.0
4          0.0      0.0      0.0      0.0  ...      0.0      0.0       0.0       0.0
...        ...      ...      ...      ...  ...      ...      ...       ...       ...
16593      0.0      0.0      0.0      0.0  ...      0.0      0.0       0.0       0.0
16594      0.0      0.0      0.0      0.0  ...      1.0      0.0       0.0       0.0
16595      0.0      0.0      0.0      0.0  ...      0.0      0.0       0.0       0.0
16596      0.0      0.0      0.0      0.0  ...      0.0      0.0       0.0       0.0
16597      0.0      0.0      0.0      0.0  ...      0.0      0.0       0.0       0.0

[16598 rows x 12 columns]

#### Get_dummies

Uwaga: warto uważać przy uzyciu `get_dummies()`, ponieważ jeśli pojawi się nowa kategoria w danych to wtedy stworzymy dla niej osobną kolumnę. A to oznacza, że liczba oraz nazwa kolumn może się nie zgadzać z naszą strukturą w wyuczonym modelu. W takich przypadkach najlepiej używać `OneHotEncoder()`, podając argument `handle_unknown="ignore"`, co pozwoli pominąć nową kategorię przy kodowaniu kategorii.

In [ ]:
# kodowanie kategorii
pd.get_dummies(df, columns=["Genre"], prefix_sep="_")

Rank  ... Genre_Strategy
0          1  ...              0
1          2  ...              0
2          3  ...              0
3          4  ...              0
4          5  ...              0
...      ...  ...            ...
16593  16596  ...              0
16594  16597  ...              0
16595  16598  ...              0
16596  16599  ...              0
16597  16600  ...              0

[16598 rows x 22 columns]

##### **Eksperyment**

###### OneHotEncoder

In [ ]:
# tworzenie inteligentnego enkodera  i przekształcenie w DF
ihot_encoder = compose.ColumnTransformer(transformers=[("encoder", 
                                                        preprocessing.OneHotEncoder(categories="auto", 
                                                                                    handle_unknown="ignore"), 
                                                        ["Genre"])], 
                                         remainder="drop")
# uczenie enkodera
fit_transformed = ihot_encoder.fit(df)
# użycie enkodera
fit_transformed.transform(df).toarray().shape

(16598, 12)

In [ ]:
# lista wartości charakterystych do transformacji
fit_transformed.get_feature_names()

['encoder__x0_Action',
 'encoder__x0_Adventure',
 'encoder__x0_Fighting',
 'encoder__x0_Misc',
 'encoder__x0_Platform',
 'encoder__x0_Puzzle',
 'encoder__x0_Racing',
 'encoder__x0_Role-Playing',
 'encoder__x0_Shooter',
 'encoder__x0_Simulation',
 'encoder__x0_Sports',
 'encoder__x0_Strategy']

In [ ]:
# tworzenie zbioru do testu
df_2 = df
df_2["Genre"][0] = "NEW"
df_2["Genre"].value_counts()

Action          3316
Sports          2345
Misc            1739
Role-Playing    1488
Shooter         1310
Adventure       1286
Racing          1249
Platform         886
Simulation       867
Fighting         848
Strategy         681
Puzzle           582
NEW                1
Name: Genre, dtype: int64

In [ ]:
# użycie z OneHotEncoder
fit_transformed.transform(df_2).toarray().shape

(16598, 12)

###### Get_dummies

In [ ]:
pd.get_dummies(df_2, columns=["Genre"]).columns

Index(['Rank', 'Name', 'Platform', 'Year', 'Publisher', 'NA_Sales', 'EU_Sales',
       'JP_Sales', 'Other_Sales', 'Global_Sales', 'Genre_Action',
       'Genre_Adventure', 'Genre_Fighting', 'Genre_Misc', 'Genre_NEW',
       'Genre_Platform', 'Genre_Puzzle', 'Genre_Racing', 'Genre_Role-Playing',
       'Genre_Shooter', 'Genre_Simulation', 'Genre_Sports', 'Genre_Strategy'],
      dtype='object')

### Przetwarzanie daty i czasu

#### Konwertowanie tekstu w datę i godzinę


In [ ]:
from IPython.display import IFrame
IFrame(src='https://strftime.org/', width=1000, height=600)

In [ ]:
# tworzenie zbioru
data_tekst = np.array(["01-01-2020 10:25 AM",
                       "03-10-2020 06:59 AM",
                       "17-12-2020 03:15 PM",
                       "11-09-2020 10:56 PM",
                       "07-03-2020 09:05 AM"])
# konwertowanie  tekstu w daty i godziny
data = pd.to_datetime(data_tekst, format="%d-%m-%Y %I:%M %p")
data

DatetimeIndex(['2020-01-01 10:25:00', '2020-10-03 06:59:00',
               '2020-12-17 15:15:00', '2020-09-11 22:56:00',
               '2020-03-07 09:05:00'],
              dtype='datetime64[ns]', freq=None)

#### Strefa czasowa

In [ ]:
# strefa czasowa Warszawa
data_warszawa = data.tz_localize("Europe/Warsaw")
print(data_warszawa)

DatetimeIndex(['2020-01-01 10:25:00+01:00', '2020-10-03 06:59:00+02:00',
               '2020-12-17 15:15:00+01:00', '2020-09-11 22:56:00+02:00',
               '2020-03-07 09:05:00+01:00'],
              dtype='datetime64[ns, Europe/Warsaw]', freq=None)


In [ ]:
# strefa czasowa london
data_warszawa.tz_convert("Europe/London")

DatetimeIndex(['2020-01-01 09:25:00+00:00', '2020-10-03 05:59:00+01:00',
               '2020-12-17 14:15:00+00:00', '2020-09-11 21:56:00+01:00',
               '2020-03-07 08:05:00+00:00'],
              dtype='datetime64[ns, Europe/London]', freq=None)

#### Zakresy dat

In [ ]:
# tworzenie zbioru danych
data_df= pd.DataFrame()
data_df["data"] = pd.date_range("1/1/2019", periods=1000, freq="H")
data_df["liczba"] = np.random.randn(1000)
data_df

data    liczba
0   2019-01-01 00:00:00 -0.609184
1   2019-01-01 01:00:00 -1.702685
2   2019-01-01 02:00:00 -0.014493
3   2019-01-01 03:00:00 -1.447434
4   2019-01-01 04:00:00  0.092774
..                  ...       ...
995 2019-02-11 11:00:00 -0.314872
996 2019-02-11 12:00:00  1.469535
997 2019-02-11 13:00:00  0.524054
998 2019-02-11 14:00:00 -0.115103
999 2019-02-11 15:00:00  0.232225

[1000 rows x 2 columns]

In [ ]:
# filtrowanie zbioru wg. zakresu dat
data_df[(data_df["data"] >= "2019-02-11 11:00:00") &
        (data_df["data"] < "2019-02-11 14:00:00")]

data    liczba
995 2019-02-11 11:00:00 -0.314872
996 2019-02-11 12:00:00  1.469535
997 2019-02-11 13:00:00  0.524054

#### Tworzenie nowych zmiennych

In [ ]:
# tworzenie próby danych
data_df_s = data_df["data"].sample(10)
data_df_s

324   2019-01-14 12:00:00
271   2019-01-12 07:00:00
386   2019-01-17 02:00:00
728   2019-01-31 08:00:00
571   2019-01-24 19:00:00
498   2019-01-21 18:00:00
712   2019-01-30 16:00:00
390   2019-01-17 06:00:00
273   2019-01-12 09:00:00
23    2019-01-01 23:00:00
Name: data, dtype: datetime64[ns]

In [ ]:
# minuty
data_df_s.dt.minute

324    0
271    0
386    0
728    0
571    0
498    0
712    0
390    0
273    0
23     0
Name: data, dtype: int64

In [ ]:
# godziny
data_df_s.dt.hour

324    12
271     7
386     2
728     8
571    19
498    18
712    16
390     6
273     9
23     23
Name: data, dtype: int64

In [ ]:
# dni
data_df_s.dt.day

324    14
271    12
386    17
728    31
571    24
498    21
712    30
390    17
273    12
23      1
Name: data, dtype: int64

In [ ]:
# miesiące
data_df_s.dt.month

324    1
271    1
386    1
728    1
571    1
498    1
712    1
390    1
273    1
23     1
Name: data, dtype: int64

In [ ]:
# lata
data_df_s.dt.year

597    2019
475    2019
986    2019
455    2019
128    2019
537    2019
245    2019
799    2019
58     2019
231    2019
Name: data, dtype: int64

In [ ]:
# dni tygodnia
data_df_s.dt.weekday

324    0
271    5
386    3
728    3
571    3
498    0
712    2
390    3
273    5
23     1
Name: data, dtype: int64

#### Obsługa braków danych w datach

In [ ]:
# tworzenie zbioru danych
data_df_m = pd.DataFrame()
data_df_m["data"] = pd.date_range("1/1/2019", periods=100, freq="H")
data_df_m["liczba"] = np.random.randint(1,10,100)
# tworzenie próby danych
data_na = data_df_m.sample(10).reset_index()
# usuwanie wartości
data_na["liczba"][1] = np.NaN
data_na["liczba"][2] = np.NaN
data_na["liczba"][3] = np.NaN
print(data_na)

   index                data  liczba
0     98 2019-01-05 02:00:00     3.0
1     44 2019-01-02 20:00:00     NaN
2      2 2019-01-01 02:00:00     NaN
3     34 2019-01-02 10:00:00     NaN
4     43 2019-01-02 19:00:00     6.0
5     33 2019-01-02 09:00:00     1.0
6     93 2019-01-04 21:00:00     1.0
7      8 2019-01-01 08:00:00     9.0
8     40 2019-01-02 16:00:00     1.0
9     65 2019-01-03 17:00:00     3.0


In [ ]:
# uzupełnienie - interpolacja
data_na.interpolate()

index                data  liczba
0     98 2019-01-05 02:00:00    3.00
1     44 2019-01-02 20:00:00    3.75
2      2 2019-01-01 02:00:00    4.50
3     34 2019-01-02 10:00:00    5.25
4     43 2019-01-02 19:00:00    6.00
5     33 2019-01-02 09:00:00    1.00
6     93 2019-01-04 21:00:00    1.00
7      8 2019-01-01 08:00:00    9.00
8     40 2019-01-02 16:00:00    1.00
9     65 2019-01-03 17:00:00    3.00

In [ ]:
# uzupełnienie wstecz
data_na.bfill()

index                data  liczba
0     98 2019-01-05 02:00:00     3.0
1     44 2019-01-02 20:00:00     6.0
2      2 2019-01-01 02:00:00     6.0
3     34 2019-01-02 10:00:00     6.0
4     43 2019-01-02 19:00:00     6.0
5     33 2019-01-02 09:00:00     1.0
6     93 2019-01-04 21:00:00     1.0
7      8 2019-01-01 08:00:00     9.0
8     40 2019-01-02 16:00:00     1.0
9     65 2019-01-03 17:00:00     3.0

In [ ]:
# uzupełnienie do przodu
data_na.ffill()

index                data  liczba
0     98 2019-01-05 02:00:00     3.0
1     44 2019-01-02 20:00:00     3.0
2      2 2019-01-01 02:00:00     3.0
3     34 2019-01-02 10:00:00     3.0
4     43 2019-01-02 19:00:00     6.0
5     33 2019-01-02 09:00:00     1.0
6     93 2019-01-04 21:00:00     1.0
7      8 2019-01-01 08:00:00     9.0
8     40 2019-01-02 16:00:00     1.0
9     65 2019-01-03 17:00:00     3.0

In [ ]:
# interpolacja z limitem wstecz
data_na.interpolate(limit=2, limit_direction="backward")

index                data  liczba
0     98 2019-01-05 02:00:00    3.00
1     44 2019-01-02 20:00:00     NaN
2      2 2019-01-01 02:00:00    4.50
3     34 2019-01-02 10:00:00    5.25
4     43 2019-01-02 19:00:00    6.00
5     33 2019-01-02 09:00:00    1.00
6     93 2019-01-04 21:00:00    1.00
7      8 2019-01-01 08:00:00    9.00
8     40 2019-01-02 16:00:00    1.00
9     65 2019-01-03 17:00:00    3.00

In [ ]:
# interpolacja różne metody
data_na.interpolate(method="slinear")

index                data  liczba
0     98 2019-01-05 02:00:00    3.00
1     44 2019-01-02 20:00:00    3.75
2      2 2019-01-01 02:00:00    4.50
3     34 2019-01-02 10:00:00    5.25
4     43 2019-01-02 19:00:00    6.00
5     33 2019-01-02 09:00:00    1.00
6     93 2019-01-04 21:00:00    1.00
7      8 2019-01-01 08:00:00    9.00
8     40 2019-01-02 16:00:00    1.00
9     65 2019-01-03 17:00:00    3.00

Inne przykładowe metody jakie można użyć:
* `linear`
* `nearest`
* `zero`
* `slinear`
* `quadratic`
* `cubic`
* `spline`
* `barycentric`
* `polynomial`

## Wykrywanie wartości odstających

In [ ]:
# tworzenie zbioru
dane_3 = np.random.randint(200,400,20)
zakupy = pd.DataFrame(dane_3, columns=["sklep1"])
print("Dane przed zastosowaniem progów:\n", zakupy)

Dane przed zastosowaniem progów:
     sklep1
0      248
1      354
2      304
3      312
4      204
5      380
6      278
7      286
8      358
9      202
10     261
11     304
12     252
13     397
14     239
15     275
16     383
17     263
18     248
19     390


In [ ]:
# tworzenie wartości odstających
zakupy["sklep1"][0] = 10
zakupy["sklep1"][1] = 700
print(zakupy)
# wizualizacja danych
px.box(zakupy, y="sklep1")

    sklep1
0       10
1      700
2      304
3      312
4      204
5      380
6      278
7      286
8      358
9      202
10     261
11     304
12     252
13     397
14     239
15     275
16     383
17     263
18     248
19     390


### Metoda 1 - EllipticEnvelope

Metoda EllipticEnvelope dopasowuje wielowymiarowy rozkład Gaussa do zbioru danych. Użyj hyperparametru `contamination`, aby określić procent obserwacji, które algorytm przypisze jako wartości odstające.

In [ ]:
# utworzenie detektora wartości odstających na podstawie elipsy wokół danych
detektor = covariance.EllipticEnvelope(contamination=0.1)
# użycie detektora
detektor.fit(zakupy)
# wykrywanie wartości odstających
flaga_odstajace = detektor.predict(zakupy)
flaga_odstajace
df_1 = df.where(flaga_odstajace == 1)
df_1.head()

NameError: ignored

In [ ]:
px.scatter(zakupy, y="sklep1", color=flaga_odstajace)

### Metoda 2 - IQR

IQR (interquartile range) - rozstęp ćwiartkowy.<br>
![IQR](https://www.statisticshowto.com/wp-content/uploads/2012/03/iqr.jpg)

In [ ]:
# tworzenie funkcji do identyfikacji anomalii
def IQR_outliers(a):
  Q1, Q3 = np.percentile(a, [25, 75])
  IQR = Q3 - Q1

  gorne_ograniczenie  = Q3 + (1.5 * IQR)
  dolne_ograniczenie  = Q1 - (1.5 * IQR)
  print("Górne ograniczenie:", gorne_ograniczenie)
  print("Dolne ograniczenie:", dolne_ograniczenie)

  indeksy = np.where((a > gorne_ograniczenie) | (a < dolne_ograniczenie))
  b = np.full(shape=a.shape[0], fill_value=1)
  b[indeksy] = -1
  print(Q1, Q3)
  return b

# użycie funkcji
flaga_IQR = IQR_outliers(zakupy["sklep1"])
print(flaga_IQR)


Górne ograniczenie: 532.25
Dolne ograniczenie: 82.25
251.0 363.5
[-1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]


In [ ]:
px.scatter(zakupy, y="sklep1", color=flaga_IQR)

## Podział zbioru na zbiór testowy i uczący 

In [ ]:
# wczytanie danych
zbior = pd.read_csv("https://bit.ly/33NOQXD", usecols=["Genre", "NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales"])
print(zbior.shape)
zbior.head(10)

(16598, 6)


Genre  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
0        Sports     41.49     29.02      3.77         8.46         82.74
1      Platform     29.08      3.58      6.81         0.77         40.24
2        Racing     15.85     12.88      3.79         3.31         35.82
3        Sports     15.75     11.01      3.28         2.96         33.00
4  Role-Playing     11.27      8.89     10.22         1.00         31.37
5        Puzzle     23.20      2.26      4.22         0.58         30.26
6      Platform     11.38      9.23      6.50         2.90         30.01
7          Misc     14.03      9.20      2.93         2.85         29.02
8      Platform     14.59      7.06      4.70         2.26         28.62
9       Shooter     26.93      0.63      0.28         0.47         28.31

In [ ]:
# tworzenie zbiorów test i train
X_train, X_test, y_train, y_test = model_selection.train_test_split(zbior.drop(columns=["Genre"]), 
                                                                    zbior["Genre"], 
                                                                    test_size=.1, 
                                                                    random_state=2020)

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14938 entries, 7699 to 9056
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   NA_Sales      14938 non-null  float64
 1   EU_Sales      14938 non-null  float64
 2   JP_Sales      14938 non-null  float64
 3   Other_Sales   14938 non-null  float64
 4   Global_Sales  14938 non-null  float64
dtypes: float64(5)
memory usage: 700.2 KB


In [ ]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1660 entries, 6636 to 6194
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   NA_Sales      1660 non-null   float64
 1   EU_Sales      1660 non-null   float64
 2   JP_Sales      1660 non-null   float64
 3   Other_Sales   1660 non-null   float64
 4   Global_Sales  1660 non-null   float64
dtypes: float64(5)
memory usage: 77.8 KB


In [ ]:
print(y_train)

7699     Role-Playing
12034            Misc
13949          Racing
6966           Sports
4599           Racing
             ...     
1661           Racing
11971          Sports
14966      Simulation
7491           Action
9056           Racing
Name: Genre, Length: 14938, dtype: object


In [ ]:
print(y_test)

6636       Sports
14473     Shooter
13860      Action
16023      Action
4293      Shooter
           ...   
13252      Action
4467     Platform
10250      Racing
15153      Sports
6194       Action
Name: Genre, Length: 1660, dtype: object
